# Generated by Django 2.2.1 on 2019-05-13 18:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RecognitionElement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to='recognition/', validators=[django.core.validators.validate_image_file_extension])),
                ('modelo', models.TextField()),
                ('descripcion', models.TextField()),
                ('month', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('year', models.IntegerField()),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
                ('mod_date', models.DateTimeField(auto_now=True)),
                ('status', models.BooleanField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Recognition Element',
            },
        ),
    ]
