# Generated by Django 2.2.1 on 2019-05-13 20:15

import django.core.validators
from django.db import migrations, models
import recognition.models


class Migration(migrations.Migration):

    dependencies = [
        ('recognition', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recognitionelement',
            name='image',
            field=models.ImageField(upload_to=recognition.models.get_upload_path, validators=[django.core.validators.validate_image_file_extension]),
        ),
        migrations.AlterField(
            model_name='recognitionelement',
            name='status',
            field=models.BooleanField(default=1),
        ),
    ]
