# Generated by Django 2.2.1 on 2019-05-14 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recognition', '0003_auto_20190514_1431'),
    ]

    operations = [
        migrations.AddField(
            model_name='recognitionelement',
            name='note_img',
            field=models.TextField(blank=True, null=True),
        ),
    ]
