# Generated by Django 2.2.1 on 2019-05-14 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recognition', '0004_recognitionelement_note_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recognitionelement',
            name='estimated_date',
            field=models.DateField(default=''),
        ),
        migrations.AlterField(
            model_name='recognitionelement',
            name='note_img',
            field=models.TextField(default=''),
        ),
    ]
