# Generated by Django 2.2.1 on 2019-05-15 21:13

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SurveyAnswers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_answer', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Survey Answers',
            },
        ),
        migrations.CreateModel(
            name='SurveysMain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('descripcion', models.TextField()),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Survey Main',
            },
        ),
        migrations.CreateModel(
            name='SurveyQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(blank=True, max_length=255, null=True)),
                ('question_image', models.ImageField(blank=True, null=True, upload_to='question_image/', validators=[django.core.validators.validate_image_file_extension])),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
                ('options_answer', models.SmallIntegerField(choices=[(0, 'Seleccion Unica'), (1, 'Seleccion Multiple'), (2, 'Texto')], default=0)),
                ('type_questions', models.SmallIntegerField(choices=[(0, 'Question Text'), (1, 'Question Image')], default=0)),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='survey_question_survey', to='surveys.SurveysMain')),
            ],
            options={
                'verbose_name_plural': 'Survey Question',
            },
        ),
        migrations.CreateModel(
            name='SurveyAnswersOptions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ansewrs_options', models.ManyToManyField(related_name='survey_answers_options', to='surveys.SurveyAnswers')),
                ('survey_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='survey_answer_question', to='surveys.SurveyQuestion')),
            ],
            options={
                'verbose_name_plural': 'Survey Answers Options',
            },
        ),
    ]
