# Generated by Django 2.2.1 on 2019-05-17 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0002_auto_20190516_1607'),
    ]

    operations = [
        migrations.AddField(
            model_name='surveyquestion',
            name='others',
            field=models.BooleanField(default=1),
        ),
    ]
