# Generated by Django 2.2.1 on 2019-05-23 21:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0004_answersquestions'),
    ]

    operations = [
        migrations.CreateModel(
            name='RelationshipQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questions_redirect', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relation_question_redirect', to='surveys.SurveyQuestion')),
                ('questions_relations', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relation_question_relation', to='surveys.SurveyQuestion')),
                ('when_answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relation_question_when_answer', to='surveys.SurveyAnswers')),
            ],
            options={
                'verbose_name_plural': 'Relationship Question',
            },
        ),
    ]
