# Generated by Django 2.2.1 on 2019-05-27 15:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0006_auto_20190523_2110'),
    ]

    operations = [
        migrations.AddField(
            model_name='surveyquestion',
            name='question_foto_firma',
            field=models.ImageField(blank=True, null=True, upload_to='question_foto_firma/', validators=[django.core.validators.validate_image_file_extension]),
        ),
        migrations.AddField(
            model_name='surveyquestion',
            name='question_html',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='surveyquestion',
            name='type_questions',
            field=models.SmallIntegerField(choices=[(0, 'Question Text'), (1, 'Question Image'), (2, 'Firma'), (3, 'Foto Firma'), (4, 'Imagen Input'), (4, 'HTML')], default=0),
        ),
    ]
