# Generated by Django 2.2.1 on 2019-05-27 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0007_auto_20190527_1559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surveyquestion',
            name='type_questions',
            field=models.SmallIntegerField(choices=[(0, 'Question Text'), (1, 'Question Image'), (2, 'Firma'), (3, 'Foto Firma'), (4, 'Imagen Input'), (5, 'HTML')], default=0),
        ),
    ]
