# Generated by Django 2.2.1 on 2019-05-09 16:36

import crud_base.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KnowledgeBase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('intro', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to=crud_base.models.get_upload_path)),
                ('status', models.IntegerField(default=0)),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('parent_id', models.IntegerField(default=0)),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
                ('mod_date', models.DateTimeField(auto_now=True)),
                ('video_url', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
