# Generated by Django 2.2.1 on 2019-05-09 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud_base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='knowledgebase',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
