# Generated by Django 2.2.1 on 2019-05-09 20:38

import crud_base.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud_base', '0002_auto_20190509_2024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='knowledgebase',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=crud_base.models.get_upload_path),
        ),
    ]
