# Generated by Django 2.2.1 on 2019-05-10 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud_base', '0003_auto_20190509_2038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='knowledgebase',
            name='video_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
